// ==== カードデータ (BASE_CARDS + CARDS) ====
// このファイルを差し替えるだけでカードの追加・修正ができます
const BASE_CARDS = {
base_defend:{id:'base_defend',name:'防御',cost:12,block:12,nextTurnEnergy:5,rarity:'N',desc:'防12 次ガッツ5',isStarter:true},
base_tameru:{id:'base_tameru',name:'ためる',cost:0,nextTurnEnergy:15,rarity:'N',desc:'次ガッツ15',isStarter:true},
motchi_b1:{mid:'motchi',id:'motchi_b1',name:'もんた',cost:10,val:8,crit:'G',rarity:'N',desc:'攻8',isStarter:true},
motchi_b2:{mid:'motchi',id:'motchi_b2',name:'もちき',cost:14,val:12,crit:'F',rarity:'N',desc:'攻12',isStarter:true},
motchi_b3:{mid:'motchi',id:'motchi_b3',name:'さくらふぶき',cost:18,val:15,vuln:2,crit:'D',rarity:'SR',desc:'攻15 守弱2',isStarter:true},
golem_b1:{mid:'golem',id:'golem_b1',name:'パンチ',cost:10,val:12,crit:'F',rarity:'N',desc:'攻12',isStarter:true},
golem_b2:{mid:'golem',id:'golem_b2',name:'キック',cost:12,val:15,crit:'E',rarity:'N',desc:'攻15',isStarter:true},
golem_b3:{mid:'golem',id:'golem_b3',name:'大パンチ',cost:18,val:23,crit:'E',rarity:'SR',desc:'攻23',isStarter:true},
mono_b1:{mid:'monolith',id:'mono_b1',name:'たいあたり',cost:8,val:13,crit:'G',rarity:'N',desc:'攻13',isStarter:true},
mono_b2:{mid:'monolith',id:'mono_b2',name:'たおれこみ',cost:10,val:17,crit:'G',rarity:'N',desc:'攻17',isStarter:true},
mono_b3:{mid:'monolith',id:'mono_b3',name:'おんぱ',cost:12,val:12,weak:2,crit:'F',rarity:'SR',desc:'攻12 攻弱2',isStarter:true},
k_b1:{mid:'kawazumo',id:'k_b1',name:'はりて',cost:10,val:11,crit:'E',rarity:'N',desc:'攻11',isStarter:true},
k_b2:{mid:'kawazumo',id:'k_b2',name:'かわずつき',cost:13,val:15,crit:'D',rarity:'N',desc:'攻15',isStarter:true},
k_b3:{mid:'kawazumo',id:'k_b3',name:'がっぷりよつ',cost:21,val:22,crit:'C',vuln:2,rarity:'SR',desc:'攻22 守弱2',isStarter:true},
ga_b1:{mid:'gali',id:'ga_b1',name:'ナックル',cost:8,val:11,crit:'E',rarity:'N',desc:'攻11',isStarter:true},
ga_b2:{mid:'gali',id:'ga_b2',name:'プレス',cost:16,val:18,crit:'F',rarity:'N',desc:'攻18',isStarter:true},
ga_b3:{mid:'gali',id:'ga_b3',name:'レッドウィスプ',cost:22,val:14,crit:'F',weak:2,vuln:2,rarity:'SR',desc:'攻14 攻弱守弱2',isStarter:true},
hinotori_b1:{mid:'hinotori',id:'hinotori_b1',name:'くちばし',cost:11,val:16,crit:'D',rarity:'N',desc:'攻16',isStarter:true},
hinotori_b2:{mid:'hinotori',id:'hinotori_b2',name:'かぎづめ',cost:8,val:13,crit:'E',rarity:'N',desc:'攻13',isStarter:true},
hinotori_b3:{mid:'hinotori',id:'hinotori_b3',name:'爆裂落とし',cost:27,val:38,crit:'B',rarity:'SR',desc:'攻38',isStarter:true},
zan_b1:{mid:'zan',id:'zan_b1',name:'レッグアーク',cost:8,val:10,crit:'E',bleed:1,rarity:'N',desc:'攻10 出血1',isStarter:true},
zan_b2:{mid:'zan',id:'zan_b2',name:'ソニックナイフ',cost:11,val:13,crit:'D',bleed:1,rarity:'N',desc:'攻13 出血1',isStarter:true},
zan_b3:{mid:'zan',id:'zan_b3',name:'血踊',cost:10,selfBleedOnHit:1,remove:true,rarity:'N',desc:'今後の攻撃時、相手に出血+1を追加 消滅',isStarter:true},
iblis_b1:{mid:'iblis',id:'iblis_b1',name:'黄泉の爪',cost:8,val:12,crit:'E',rarity:'N',desc:'攻12',isStarter:true},
iblis_b2:{mid:'iblis',id:'iblis_b2',name:'光刃',cost:11,val:13,crit:'D',formTo:'angel',rarity:'N',desc:'攻13 使用後 天使型になる',isStarter:true},
iblis_b3:{mid:'iblis',id:'iblis_b3',name:'反転の型',cost:14,val:14,block:16,crit:'E',formTo:'toggle',rarity:'SR',desc:'攻14 防16 使用後 形態が入れ替わる',isStarter:true},

// ==== スキン専用の初期技 ====
// SSRスキンを「所持していれば」装備画面で選べる、種族の看板技(b3)の差し替え版。
// 装備中のスキンとは無関係に選べるので、見た目はSRスキンのまま技だけ変える、といった使い方ができる。
// 上位互換ではなく差し替え(コストと火力を落とす代わりに効果を足す等)になるよう調整してある。
//   skinCardOf : この技を解放するスキンのid
//   replaces   : 初期デッキの中で置き換える対象のカードid
// CARDSではなくBASE_CARDSにだけ置いてあるのが重要。CARDSに入れると
// カード報酬・ショップ・イベントの抽選対象になり、スキン未所持でも入手できてしまう。
motchi_b3_skin:{mid:'motchi',id:'motchi_b3_skin',name:'天使の舞',cost:13,val:10,vuln:2,heal:2,crit:'D',rarity:'SR',desc:'攻10 守弱2 回2',isStarter:true,skinCardOf:'motchi_ssr_01',replaces:'motchi_b3'},
golem_b3_skin:{mid:'golem',id:'golem_b3_skin',name:'氷晶の鉄拳',cost:16,val:21,freeze:1,crit:'E',rarity:'SR',desc:'攻21 氷結1',isStarter:true,skinCardOf:'golem_ssr_01',replaces:'golem_b3'},
golem_b3_skin2:{mid:'golem',id:'golem_b3_skin2',name:'スピリットパンチ',cost:12,val:28,weak:2,crit:'C',rarity:'SR',desc:'攻28 攻弱2',isStarter:true,skinCardOf:'golem_ssr_02',replaces:'golem_b3'},
mono_b3_skin:{mid:'monolith',id:'mono_b3_skin',name:'翠玉の頁',cost:12,val:11,weak:2,nextTurnEnergy:5,crit:'F',rarity:'SR',desc:'攻11 攻弱2 次ガッツ5',isStarter:true,skinCardOf:'monolith_ssr_01',replaces:'mono_b3'},
mono_b3_skin2:{mid:'monolith',id:'mono_b3_skin2',name:'魔王の雄叫び',cost:20,val:35,freeze:1,shock:1,crit:'E',rarity:'SR',desc:'攻35 氷結1 感電1',isStarter:true,skinCardOf:'monolith_ssr_02',replaces:'mono_b3'},
k_b3_skin:{mid:'kawazumo',id:'k_b3_skin',name:'がっぷりよつ蒼',cost:15,val:17,vuln:2,block:8,crit:'C',rarity:'SR',desc:'攻17 守弱2 防8',isStarter:true,skinCardOf:'kawazumo_ssr_01',replaces:'k_b3'},
ga_b3_skin:{mid:'gali',id:'ga_b3_skin',name:'深淵の焔',cost:22,val:12,weak:2,vuln:2,burn:2,crit:'F',rarity:'SR',desc:'攻12 攻弱守弱2 炎上2',isStarter:true,skinCardOf:'gali_ssr_01',replaces:'ga_b3'},
hinotori_b3_skin:{mid:'hinotori',id:'hinotori_b3_skin',name:'黄金雷撃',cost:27,val:32,shock:2,crit:'B',rarity:'SR',desc:'攻32 感電2',isStarter:true,skinCardOf:'hinotori_ssr_01',replaces:'hinotori_b3'},
zan_b3_skin:{mid:'zan',id:'zan_b3_skin',name:'溶岩の型',cost:13,burn:2,selfBleedOnHit:1,remove:true,rarity:'N',desc:'炎上2 今後の攻撃時、相手に出血+1を追加 消滅',isStarter:true,skinCardOf:'zan_ssr_01',replaces:'zan_b3'},
hinotori_b3_skin2:{mid:'hinotori',id:'hinotori_b3_skin2',name:'ハデスフレア',cost:21,val:29,burn:2,bleed:3,crit:'B',rarity:'SR',desc:'攻29 炎上2 出血3',isStarter:true,skinCardOf:'hinotori_ssr_02',replaces:'hinotori_b3'},
motchi_b3_skin2:{mid:'motchi',id:'motchi_b3_skin2',name:'無下限呪術',cost:9,val:14,block:25,weak:2,crit:'A',rarity:'SR',desc:'攻14 防25 攻弱2',isStarter:true,skinCardOf:'motchi_ssr_02',replaces:'motchi_b3'},
k_b3_skin2:{mid:'kawazumo',id:'k_b3_skin2',name:'呪霊操術',cost:16,val:18,vuln:1,curse:3,crit:'C',rarity:'SR',desc:'攻18 守弱1 呪霊+3',isStarter:true,skinCardOf:'kawazumo_ssr_02',replaces:'k_b3'},
// ライオネル(iblis_ssr_01)の看板技。反転の型と同じ往復札だが、
// 通常形態=守って昇る / 天使型=殴って降りる と、形態で役割が変わる。
// 【重要】初期デッキで通常形態に戻れるのはこの1枚だけ。formTo:'toggle' を外さないこと。
iblis_b3_skin:{mid:'iblis',id:'iblis_b3_skin',name:'獅子と熾天',cost:12,val:12,block:22,crit:'D',formTo:'toggle',
  formEff:{angel:{val:28,block:6,crit:'C'}},rarity:'SR',
  desc:'攻12 防22 使用後 形態が入れ替わる 【天】攻28 防6',isStarter:true,skinCardOf:'iblis_ssr_01',replaces:'iblis_b3'},
};
const CARDS = {
hinotori_b1:{mid:'hinotori',id:'hinotori_b1',name:'くちばし',cost:11,val:16,crit:'D',rarity:'N',desc:'攻16',isStarter:true},
hinotori_b2:{mid:'hinotori',id:'hinotori_b2',name:'かぎづめ',cost:8,val:13,crit:'E',rarity:'N',desc:'攻13',isStarter:true},
hinotori_b3:{mid:'hinotori',id:'hinotori_b3',name:'爆裂落とし',cost:27,val:38,crit:'B',rarity:'SR',desc:'攻38',isStarter:true},
h_n1:{mid:'hinotori',name:'雄叫び',cost:19,val:19,crit:'F',weak:2,vuln:2,rarity:'N',desc:'攻19 2T攻弱守弱'},
h_n2:{mid:'hinotori',name:'ファイアキャノン',cost:17,val:26,crit:'D',weak:1,rarity:'N',desc:'攻26 1T攻弱'},
h_n3:{mid:'hinotori',name:'羽根ビンタ',cost:10,val:18,crit:'E',rarity:'N',desc:'攻18'},
h_n4:{mid:'hinotori',name:'火の粉浴び',cost:14,heal:10,atkBattle:3,remove:true,rarity:'N',desc:'回10 力3 消滅'},
h_r1:{mid:'hinotori',name:'フレイムビーム',cost:22,val:39,crit:'G',rarity:'R',desc:'攻39'},
h_r2:{mid:'hinotori',name:'フレイムライン',cost:28,val:35,crit:'A',vuln:3,rarity:'R',desc:'攻35 3T守弱'},
h_r3:{mid:'hinotori',name:'ウィングブレード',cost:17,val:24,crit:'B',block:14,rarity:'R',desc:'攻24 防14'},
h_r4:{mid:'hinotori',name:'ファイアオーラ',cost:11,regenEnergy:5,regenBlock:5,remove:true,rarity:'R',desc:'毎G5 毎防5 消滅'},
h_r5:{mid:'hinotori',name:'フレイムウォール',cost:17,block:27,nextTurnEnergy:15,rarity:'R',desc:'防27 次ガッツ15'},
h_sr1:{mid:'hinotori',name:'ヴェノムクロウ',cost:27,val:38,crit:'D',vuln:2,bleed:10,rarity:'SR',desc:'攻38 守弱2 出血10'},
h_sr2:{mid:'hinotori',name:'連続かぎづめ',cost:23,val:17,crit:'D',hits:2,rarity:'SR',desc:'攻17 連撃2'},
h_sr3:{mid:'hinotori',name:'ファイヤーバード',cost:40,val:55,crit:'D',burn:1,rarity:'SR',desc:'攻55 炎上1'},
h_sr4:{mid:'hinotori',name:'ラヴァウォール',cost:20,block:38,nextTurnEnergy:30,burn:1,rarity:'SR',desc:'防38 次ガッツ30 炎上1'},
h_sr5:{mid:'hinotori',name:'フレイムオーラ',cost:15,regenEnergy:10,regenHp:3,atkBattle:3,blockBattle:3,draw:1,remove:true,rarity:'SR',desc:'毎G10 毎HP3 力丈+3 ドロー1 消滅'},
h_ssr1:{mid:'hinotori',name:'フレイムタイフーン',cost:30,val:7,crit:'A',hits:4,rarity:'SSR',desc:'攻7 連撃4'},
h_ssr2:{mid:'hinotori',name:'エタニティフレア',cost:45,val:58,crit:'D',freeze:1,burn:1,rarity:'SSR',desc:'攻58 氷結1 炎上1'},
h_ssr3:{mid:'hinotori',name:'ファントムブレイク',cost:40,val:8,crit:'C',hits:4,vuln:1,rarity:'SSR',desc:'攻8 連撃4 守弱1'},
h_ssr4:{mid:'hinotori',name:'再生の炎',cost:55,heal:40,block:27,atkBattle:2,rarity:'SSR',desc:'回40 防27 力2'},
h_ssr5:{mid:'hinotori',name:'ファイアリバー',cost:45,val:64,crit:'C',burn:1,rarity:'SSR',desc:'攻64 炎上1'},
h_mr1:{mid:'hinotori',name:'ファイアウェーブ',cost:58,val:40,crit:'B',hits:2,burn:1,rarity:'MR',desc:'攻40 連撃2 炎上1 炎上中の敵に使うとガッツ回復15'},
h_mr2:{mid:'hinotori',name:'エボニーノヴァ',cost:61,val:14,crit:'B',hits:3,atkBattle:2,blockBattle:2,rarity:'MR',desc:'攻14 連撃3 力丈+2'},
h_mr3:{mid:'hinotori',name:'アブソリュートゼロ',cost:54,val:81,crit:'A',freeze:2,vuln:2,rarity:'MR',desc:'攻81 氷結2 守弱2'},
h_mr4:{mid:'hinotori',name:'伝説の不死鳥',cost:50,regenEnergy:15,regenHp:5,heal:50,block:50,draw:2,regenDraw:1,remove:true,rarity:'MR',desc:'毎G15 毎HP5 回50 防50 2ドロー 毎ドロー1 消滅'},
m_n1:{mid:'motchi',name:'もっちゃん',cost:15,val:24,crit:'G',block:7,rarity:'N',desc:'攻24 防7',img:'img/cards/m_n1.png'},
m_n2:{mid:'motchi',name:'ローリン',cost:19,val:24,crit:'F',draw:1,rarity:'N',desc:'攻24 1ドロー'},
m_n3:{mid:'motchi',name:'ぺろりん',cost:16,val:8,crit:'E',weak:2,rarity:'N',desc:'攻8 2T攻弱'},
m_n4:{mid:'motchi',name:'あまえる',cost:0,weak:1,vuln:1,rarity:'N',desc:'1T攻弱 1T守弱'},
m_n5:{mid:'motchi',name:'元気っちー！',cost:16,heal:5,block:7,regenEnergy:3,remove:true,rarity:'N',desc:'回5 防7 毎G3 消滅'},
m_r1:{mid:'motchi',name:'ローリンローリン',cost:21,val:14,hits:2,crit:'E',rarity:'R',desc:'攻14 連撃2'},
m_r2:{mid:'motchi',name:'もっちり',cost:17,val:15,crit:'D',block:8,weak:1,rarity:'R',desc:'攻15 防8 攻弱1'},
m_r3:{mid:'motchi',name:'さくら猛ふぶき',cost:26,val:8,hits:3,crit:'B',vuln:1,rarity:'R',desc:'攻8 1T守弱 連撃3'},
m_r4:{mid:'motchi',name:'モン刺し',cost:13,val:12,crit:'A',combo:true,rarity:'R',desc:'攻12 守弱時ガッツ7回'},
m_r5:{mid:'motchi',name:'ふんばり',cost:7,block:17,regenEnergy:3,remove:true,rarity:'R',desc:'防17 毎ガッツ3 消滅'},
m_r6:{mid:'motchi',name:'もっさん',cost:22,val:36,crit:'E',block:13,rarity:'R',desc:'攻36 防13'},
m_r7:{mid:'motchi',name:'ガッツだっちー！',cost:0,instantEnergy:10,maxEnergyBattle:15,remove:true,rarity:'R',desc:'ガッツ10回 上限15 消滅'},
m_sr1:{mid:'motchi',name:'ガッチャー',cost:24,val:17,hits:2,crit:'D',rarity:'SR',desc:'攻17 連撃2'},
m_sr2:{mid:'motchi',name:'超ローリンモッチ',cost:33,val:44,crit:'A',critEnergy:7,rarity:'SR',desc:'攻44 会心時ガッツ回復7'},
m_sr3:{mid:'motchi',name:'乱れざくら',cost:36,val:14,hits:3,draw:1,rarity:'SR',desc:'攻14 連撃3 1ドロー'},
m_sr4:{mid:'motchi',name:'八重ざくら',cost:45,heal:20,regenEnergy:7,remove:true,rarity:'SR',desc:'回20 毎ガッツ7 消滅'},
m_sr5:{mid:'motchi',name:'大モッチ砲',cost:33,val:40,crit:'B',vuln:2,burn:1,rarity:'SR',desc:'攻40 2T守弱 炎上1'},
m_sr6:{mid:'motchi',name:'超集中',cost:28,nextTurnDouble:true,rarity:'SR',desc:'次ターン与ダメ2倍'},
m_sr7:{mid:'motchi',name:'冷静沈着',cost:5,block:8,draw:2,rarity:'SR',desc:'防8 ドロー2'},
m_sr8:{mid:'motchi',name:'変動床',cost:5,blockBattle:3,regenEnergy:5,remove:true,rarity:'SR',desc:'丈3 毎ガッツ5 消滅'},
m_ssr1:{mid:'motchi',name:'もっさま',cost:36,val:55,crit:'C',block:22,critEnergy:20,rarity:'SSR',desc:'攻55 防22 会心時ガッツ20'},
m_ssr2:{mid:'motchi',name:'超モッチ砲',cost:42,val:52,crit:'A',vuln:3,burn:2,rarity:'SSR',desc:'攻52 3T守弱 炎上2'},
m_ssr3:{mid:'motchi',name:'超ガッチョ',cost:45,val:16,hits:3,crit:'C',comboEnergy:10,rarity:'SSR',desc:'攻16 連撃3 攻弱時ガッツ回復10'},
m_ssr4:{mid:'motchi',name:'宵闇ざくら',cost:48,val:15,hits:4,heal:10,crit:'F',rarity:'SSR',desc:'攻15 連撃4 回10'},
m_ssr5:{mid:'motchi',name:'欲張りっちー！',cost:10,draw:2,regenDraw:1,regenEnergy:5,maxEnergyBattle:20,remove:true,rarity:'SSR',desc:'ドロー2 毎ターンドロー1 毎G5 上限20 消滅'},
m_mr1:{mid:'motchi',name:'ガッツ全開っちー！',cost:0,instantEnergy:99,draw:2,remove:true,rarity:'MR',desc:'ガッツ99 2ドロー 消滅'},
m_mr2:{mid:'motchi',name:'極モッチ砲',cost:50,val:60,crit:'S',weak:3,vuln:3,burn:2,rarity:'MR',desc:'攻60 3T攻弱守弱 炎上2'},
m_mr3:{mid:'motchi',name:'ガッチェスト',cost:60,val:14,hits:4,crit:'B',weakCombo:25,rarity:'MR',desc:'攻14 連撃4 攻弱時ガッツ25回'},
g_n1:{mid:'golem',name:'でこぴん',cost:18,val:22,crit:'A',rarity:'N',desc:'攻22',img:'img/cards/g_n1.png'},
g_n2:{mid:'golem',name:'チョップ',cost:24,val:30,crit:'D',rarity:'N',desc:'攻30'},
g_n3:{mid:'golem',name:'なでる',cost:10,val:18,crit:'G',rarity:'N',desc:'攻18'},
g_n4:{mid:'golem',name:'岩投げ',cost:28,val:30,crit:'E',block:6,rarity:'N',desc:'攻30 防6'},
g_n5:{mid:'golem',name:'なごむ',cost:10,heal:5,nextTurnEnergy:10,rarity:'N',desc:'回5 次ガッツ10'},
g_r1:{mid:'golem',name:'大キック',cost:28,val:38,crit:'E',weak:2,rarity:'R',desc:'攻38 2T攻弱'},
g_r2:{mid:'golem',name:'掌打',cost:30,val:40,crit:'D',block:7,comboDmg:15,rarity:'R',desc:'攻40 防7 守弱時ダメージ15'},
g_r3:{mid:'golem',name:'地震',cost:18,val:18,crit:'F',vuln:2,rarity:'R',desc:'攻18 2T守弱'},
g_r4:{mid:'golem',name:'タックル',cost:30,val:34,block:14,crit:'C',rarity:'R',desc:'攻34 防14'},
g_r5:{mid:'golem',name:'ビンタ',cost:14,val:22,crit:'E',vuln:1,rarity:'R',desc:'攻22 守弱1'},
g_r6:{mid:'golem',name:'たえる',cost:8,block:10,atkBattle:1,blockBattle:1,nextTurnEnergy:15,rarity:'R',desc:'防10 力1 丈夫さ1 次ガッツ15'},
g_r7:{mid:'golem',name:'ドミノ倒し',cost:3,atkBattle:5,remove:true,rarity:'R',desc:'力5 消滅'},
g_sr1:{mid:'golem',name:'大でこぴん',cost:28,val:38,crit:'S',draw:1,atkBattle:1,rarity:'SR',desc:'攻38 ドロー1 力1'},
g_sr2:{mid:'golem',name:'フライングプレス',cost:30,val:64,selfDmg:8,crit:'E',rarity:'SR',desc:'攻64 自傷8'},
g_sr3:{mid:'golem',name:'合掌',cost:28,val:25,crit:'C',weak:2,vuln:2,rarity:'SR',desc:'攻25 2T攻弱守弱'},
g_sr4:{mid:'golem',name:'ダブルチョップ',cost:40,val:26,hits:2,crit:'C',rarity:'SR',desc:'攻26 連撃2'},
g_sr5:{mid:'golem',name:'大ビンタ',cost:21,val:33,crit:'D',vuln:1,rarity:'SR',desc:'攻33 守弱1'},
g_sr6:{mid:'golem',name:'重り引き',cost:5,atkBattle:8,remove:true,rarity:'SR',desc:'力8 消滅'},
g_ssr1:{mid:'golem',name:'ぐるぐるアタック',cost:50,val:69,crit:'D',block:30,comboDmg:25,rarity:'SSR',desc:'攻69 防30 守弱時25'},
g_ssr2:{mid:'golem',name:'竜巻アタック',cost:55,val:25,hits:3,crit:'B',rarity:'SSR',desc:'攻25 連撃3'},
g_ssr3:{mid:'golem',name:'大ハエタタキ',cost:42,val:55,crit:'B',weak:3,critEnergy:20,rarity:'SSR',desc:'攻55 3T攻弱 会心時ガッツ回復20'},
g_ssr4:{mid:'golem',name:'超我慢',cost:22,block:30,nextTurnEnergy:35,rarity:'SSR',desc:'防30 次ガッツ35'},
g_mr1:{mid:'golem',name:'全身全霊',cost:10,atkBattle:5,blockBattle:5,currentTurnDouble:true,currentTurnBlockDouble:true,regenEnergy:5,remove:true,rarity:'MR',desc:'力丈+5 このターンダメージ2倍、ブロック2倍 毎G5 消滅'},
g_mr2:{mid:'golem',name:'超竜巻アタック',cost:65,val:24,hits:4,crit:'C',rarity:'MR',desc:'攻24 連撃4'},
g_mr3:{mid:'golem',name:'瞑想',cost:12,heal:10,atkBattle:3,blockBattle:3,regenEnergy:15,remove:true,rarity:'MR',desc:'回10 力丈+3 毎G15 消滅'},
mo_n1:{mid:'monolith',name:'ひっかき',cost:11,val:13,crit:'E',weak:1,rarity:'N',desc:'攻13 1T攻弱',img:'img/cards/mo_n1.png'},
mo_n2:{mid:'monolith',name:'トリオビームX',cost:21,val:25,crit:'C',blockBattle:1,rarity:'N',desc:'攻25 丈+1'},
mo_n3:{mid:'monolith',name:'大たおれこみ',cost:15,val:19,crit:'F',block:5,rarity:'N',desc:'攻19 防5'},
mo_n4:{mid:'monolith',name:'怪光線',cost:16,val:12,crit:'C',vuln:1,rarity:'N',desc:'攻12 1T守弱'},
mo_n5:{mid:'monolith',name:'鉄壁',cost:5,block:20,remove:true,rarity:'N',desc:'防20 消滅'},
mo_r1:{mid:'monolith',name:'針ぶっ刺し',cost:17,val:28,crit:'F',block:5,rarity:'R',desc:'攻28 防5'},
mo_r2:{mid:'monolith',name:'トリオビームY',cost:26,val:30,crit:'C',draw:1,blockBattle:1,rarity:'R',desc:'攻30 ドロー1 丈+1'},
mo_r3:{mid:'monolith',name:'わらひっかき',cost:20,val:18,crit:'F',weak:2,vuln:2,rarity:'R',desc:'攻18 2T攻弱守弱'},
mo_r4:{mid:'monolith',name:'はさみこみ',cost:19,val:13,hits:2,crit:'D',block:10,rarity:'R',desc:'攻13 防10 連撃2'},
mo_r5:{mid:'monolith',name:'ぬりかべ',cost:5,block:30,heal:10,blockBattle:3,remove:true,rarity:'R',desc:'防30 回10 丈+3 消滅'},
mo_sr1:{mid:'monolith',name:'わらわら',cost:28,val:33,crit:'D',weak:2,vuln:2,rarity:'SR',desc:'攻33 2T攻弱守弱'},
mo_sr2:{mid:'monolith',name:'超針ぶっ刺し',cost:32,val:42,crit:'D',block:20,rarity:'SR',desc:'攻42 防20'},
mo_sr3:{mid:'monolith',name:'超たおれこみ',cost:18,val:27,crit:'C',block:11,rarity:'SR',desc:'攻27 防11'},
mo_sr4:{mid:'monolith',name:'サケビ声',cost:21,val:15,crit:'E',weak:3,breakBlock:true,rarity:'SR',desc:'攻15 3T攻弱 破壊'},
mo_sr5:{mid:'monolith',name:'超鉄壁',cost:10,block:47,nextTurnEnergy:25,remove:true,rarity:'SR',desc:'防47 次ガッツ25 消滅'},
mo_sr6:{mid:'monolith',name:'プール',cost:5,blockBattle:5,remove:true,rarity:'SR',desc:'丈5 消滅'},
mo_ssr1:{mid:'monolith',name:'トリオビームZ',cost:34,val:35,crit:'S',block:21,draw:2,blockBattle:1,rarity:'SSR',desc:'攻35 防21 ドロー2 丈+1'},
mo_ssr2:{mid:'monolith',name:'フォームガンマ',cost:45,val:18,hits:3,crit:'C',nextTurnEnergy:15,rarity:'SSR',desc:'攻18 連撃3 次ガッツ15'},
mo_ssr3:{mid:'monolith',name:'3連アタック',cost:49,val:20,hits:3,crit:'F',block:15,rarity:'SSR',desc:'攻20 連撃3 防15'},
mo_ssr4:{mid:'monolith',name:'賢者の教え',cost:13,block:13,regenHp:2,regenEnergy:5,remove:true,rarity:'SSR',desc:'防13 毎HP2G5回 消滅'},
mo_mr1:{mid:'monolith',name:'かどみうむの祝福',cost:20,block:20,blockBattle:5,regenEnergy:15,remove:true,rarity:'MR',desc:'防20 丈5 毎ガッツ15 消滅'},
mo_mr2:{mid:'monolith',name:'オーロラゲート',cost:33,val:48,crit:'D',block:27,vuln:3,rarity:'MR',desc:'攻48 防27 3T守弱'},
mo_mr3:{mid:'monolith',name:'アビスゲート',cost:55,val:74,crit:'B',heal:15,nextTurnEnergy:15,rarity:'MR',desc:'攻74 回15 次ガッツ15'},
// Kawazumo
k_n1:{mid:'kawazumo',name:'とびはりて',cost:12,val:19,crit:'F',rarity:'N',desc:'攻19',img:'img/cards/k_n1.png'},
k_n2:{mid:'kawazumo',name:'どっこい！',cost:16,val:34,crit:'E',selfDmg:5,rarity:'N',desc:'攻34 自傷5'},
k_n3:{mid:'kawazumo',name:'目潰し',cost:12,val:8,crit:'F',weak:2,rarity:'N',desc:'攻8 2T攻弱'},
k_n4:{mid:'kawazumo',name:'土俵入り',cost:13,block:8,nextTurnEnergy:18,rarity:'N',desc:'防8 次G18'},
k_r1:{mid:'kawazumo',name:'かえるのした',cost:13,val:16,crit:'D',vuln:1,rarity:'R',desc:'攻16 守弱1'},
k_r2:{mid:'kawazumo',name:'かえるのうた',cost:25,val:4,crit:'F',weak:3,vuln:3,rarity:'R',desc:'攻4 3T攻弱守弱'},
k_r3:{mid:'kawazumo',name:'大はりて',cost:16,val:24,crit:'F',block:8,rarity:'R',desc:'攻24 防8'},
k_r4:{mid:'kawazumo',name:'しこふんばり',cost:7,block:15,nextTurnEnergy:15,rarity:'R',desc:'防15 次G15'},
k_sr1:{mid:'kawazumo',name:'連続はりて',cost:26,val:8,hits:4,crit:'E',rarity:'SR',desc:'攻8 連撃4'},
k_sr2:{mid:'kawazumo',name:'爆弾投げ',cost:30,val:39,crit:'B',burn:1,rarity:'SR',desc:'攻39 炎上1'},
k_sr3:{mid:'kawazumo',name:'上手投げ',cost:24,val:36,crit:'C',draw:1,rarity:'SR',desc:'攻36 1ドロー'},
k_sr4:{mid:'kawazumo',name:'四股踏み',cost:35,val:36,crit:'B',block:18,nextTurnEnergy:18,rarity:'SR',desc:'攻36 防18 次G18'},
k_sr5:{mid:'kawazumo',name:'はっきよーい',cost:0,selfDmg:15,nextTurnDouble:true,nextTurnEnergy:25,rarity:'SR',desc:'自傷15 次与ダメ2倍 次G25'},
k_ssr1:{mid:'kawazumo',name:'大投げたまや',cost:38,val:80,crit:'B',selfDmg:11,rarity:'SSR',desc:'攻80 自傷11'},
k_ssr2:{mid:'kawazumo',name:'大回転落とし',cost:49,val:56,crit:'C',block:32,rarity:'SSR',desc:'攻56 防32'},
k_ssr3:{mid:'kawazumo',name:'ゴールドラッシュ',cost:41,val:14,hits:3,crit:'A',critEnergy:10,rarity:'SSR',desc:'攻14 連撃3 会心時ガッツ回復10'},
k_ssr4:{mid:'kawazumo',name:'かわずシールド',cost:22,block:40,nextTurnEnergy:30,rarity:'SSR',desc:'防40 次G30'},
k_ssr5:{mid:'kawazumo',name:'ごっつぁんです',cost:50,heal:50,regenEnergy:8,remove:true,rarity:'SSR',desc:'回50 毎G8 消滅'},
k_mr1:{mid:'kawazumo',name:'かわずラッシュ',cost:58,val:22,hits:3,crit:'C',block:21,draw:2,rarity:'MR',desc:'攻22 連撃3 防21 2ドロー'},
k_mr2:{mid:'kawazumo',name:'大爆発カワズモー',cost:99,val:120,hits:4,crit:'A',selfDmg:120,rarity:'MR',desc:'攻120 連撃4 自傷120'},
k_mr3:{mid:'kawazumo',name:'ライモン会の横綱',cost:14,regenHp:5,regenEnergy:11,remove:true,rarity:'MR',desc:'毎HP5 毎G11 消滅'},

// Gali
ga_n1:{mid:'gali',name:'落雷',cost:10,val:8,crit:'E',shock:1,rarity:'N',desc:'攻8 感電1',img:'img/cards/ga_n1.png'},
ga_n2:{mid:'gali',name:'火のかべ',cost:18,val:16,crit:'F',burn:1,rarity:'N',desc:'攻16 炎上1'},
ga_n3:{mid:'gali',name:'ストレート',cost:13,val:20,crit:'F',rarity:'N',desc:'攻20'},
ga_n4:{mid:'gali',name:'お祈り',cost:5,heal:5,nextTurnEnergy:18,remove:true,rarity:'N',desc:'回5 次G18 消滅'},
ga_r1:{mid:'gali',name:'ハリケーン',cost:18,val:28,crit:'E',rarity:'R',desc:'攻28'},
ga_r2:{mid:'gali',name:'スピンカッター',cost:16,val:15,crit:'B',critEnergy:7,rarity:'R',desc:'攻15 会心時ガッツ回復7'},
ga_r3:{mid:'gali',name:'炎のかべ',cost:25,val:26,crit:'E',burn:1,rarity:'R',desc:'攻26 炎上1'},
ga_r4:{mid:'gali',name:'バリアー',cost:11,block:25,nextTurnEnergy:5,rarity:'R',desc:'防25 次G5'},
ga_sr1:{mid:'gali',name:'魔人ハリケーン',cost:32,val:49,crit:'D',draw:1,rarity:'SR',desc:'攻49 1ドロー'},
ga_sr2:{mid:'gali',name:'大スピンカッター',cost:20,val:28,crit:'A',vuln:2,critEnergy:10,rarity:'SR',desc:'攻28 守弱2 会心時ガッツ回復10'},
ga_sr3:{mid:'gali',name:'ブルーウィスプ',cost:27,val:8,crit:'F',weak:3,vuln:3,burn:1,rarity:'SR',desc:'攻8 3T攻守弱 炎上1'},
ga_sr4:{mid:'gali',name:'ホーリーサンダー',cost:28,val:19,crit:'C',shock:2,rarity:'SR',desc:'攻19 感電2'},
ga_sr5:{mid:'gali',name:'ホーリーファイアー',cost:33,val:42,crit:'D',burn:2,rarity:'SR',desc:'攻42 炎上2'},
ga_sr6:{mid:'gali',name:'ホーリーアイシクル',cost:26,val:25,crit:'B',freeze:2,rarity:'SR',desc:'攻25 氷結2'},
ga_sr7:{mid:'gali',name:'神の祈り',cost:13,regenHp:2,regenEnergy:8,exhaust:true,rarity:'SR',desc:'毎HP2 毎G8 消滅'},
ga_ssr1:{mid:'gali',name:'ゴッドハリケーン',cost:42,val:55,crit:'C',draw:1,rarity:'SSR',desc:'攻55 1ドロー'},
ga_ssr2:{mid:'gali',name:'ゴッドプレス',cost:45,val:69,crit:'D',rarity:'SSR',desc:'攻69'},
ga_ssr3:{mid:'gali',name:'ゴッドエレメンタル',cost:65,val:37,crit:'C',weak:1,vuln:1,burn:1,freeze:1,shock:1,rarity:'SSR',desc:'攻37 攻守弱炎結雷1'},
ga_ssr4:{mid:'gali',name:'ゴッドファイナル',cost:31,val:65,crit:'S',block:35,regenEnergy:5,remove:true,rarity:'SSR',desc:'攻65 防35 毎G5 消滅'},
ga_mr1:{mid:'gali',name:'ゴッドブレス',cost:49,val:33,hits:2,crit:'B',vuln:1,draw:1,rarity:'MR',desc:'攻33 連撃2 守弱1 1ドロー'},
ga_mr2:{mid:'gali',name:'ゴッドライジング',cost:62,val:25,crit:'C',godRising:true,rarity:'MR',desc:'攻25 敵の異常種数連撃'},
ga_mr3:{mid:'gali',name:'ゴッドフォース',cost:0,instantEnergy:50,regenHp:5,regenEnergy:10,remove:true,rarity:'MR',desc:'G50 毎HP5 毎G10 消滅'},

c_n1:{name:'ガード',cost:8,block:10,nextTurnEnergy:7,rarity:'N',desc:'防10 次ガッツ7'},
c_n2:{name:'緊急回復',cost:20,discardTwo:true,heal:5,nextTurnEnergy:10,rarity:'N',desc:'2枚捨 回5 次ガッツ10'},
c_n3:{name:'いじわる',cost:22,val:15,combo:true,rarity:'N',desc:'攻15 守弱時ガッツ10回'},
c_n4:{name:'ふきとばし',cost:10,val:15,block:15,rarity:'N',desc:'攻15 防15'},
// コスト0でドロー1・消滅なしだったため、使っても手札が減らず無限にデッキを掘れてしまっていた。
// 「消滅」を付けてループを断ち、その代わりドローを2枚に増やしている。
c_n5:{name:'ドロー！！',cost:0,draw:2,remove:true,rarity:'N',desc:'ドロー2 消滅'},
c_r1:{name:'一閃',cost:15,val:20,crit:'C',rarity:'R',desc:'攻20'},
c_r2:{name:'振りかぶり',cost:16,nextAtkBonusMult:2,rarity:'R',desc:'次与ダメ2倍'},
c_r3:{name:'わるぐち',cost:12,weak:2,vuln:2,rarity:'R',desc:'2T攻弱守弱'},
c_r4:{name:'力トレーニング',cost:5,atkBattle:3,remove:true,rarity:'R',desc:'力3 消滅'},
c_r5:{name:'丈夫さトレーニング',cost:5,blockBattle:3,remove:true,rarity:'R',desc:'丈3 消滅'},
c_r6:{name:'仕切り直し',cost:21,discardAll:true,draw:5,rarity:'R',desc:'手札全捨て ドロー5'},
c_r7:{name:'ハイガード',cost:15,block:22,nextTurnEnergy:10,rarity:'R',desc:'防22 次ガッツ10'},
c_r8:{name:'ガッツヒール',cost:0,instantEnergy:8,rarity:'R',desc:'ガッツ8回復'},
c_sr1:{name:'超一閃',cost:22,val:35,crit:'B',rarity:'SR',desc:'攻35'},
c_sr2:{name:'EXトレーニング',cost:15,atkBattle:4,blockBattle:4,remove:true,rarity:'SR',desc:'力4 丈4 消滅'},
c_sr3:{name:'超ガード',cost:19,block:32,nextTurnEnergy:15,rarity:'SR',desc:'防32 次ガッツ15'},
c_sr4:{name:'入れ替え',cost:5,discardTwo:true,draw:3,rarity:'SR',desc:'2枚捨て ドロー3'},
c_sr5:{name:'超ガッツヒール',cost:0,instantEnergy:15,rarity:'SR',desc:'ガッツ15回復'},
c_ssr1:{name:'シールドブーメラン',cost:21,val:15,hits:2,crit:'C',block:20,rarity:'SSR',desc:'攻15 防20 連撃2'},
c_ssr2:{name:'弱点集中',cost:39,val:38,comboEnergy:20,rarity:'SSR',desc:'攻38 守弱時ガッツ20回'},
c_ssr3:{name:'爆裂掌',cost:46,val:13,hits:4,crit:'C',rarity:'SSR',desc:'攻13 連撃4'},
c_ssr4:{name:'緊急回避',cost:20,block:100,remove:true,rarity:'SSR',desc:'防100 消滅'},
c_ssr5:{name:'極ガード',cost:21,block:45,nextTurnEnergy:25,rarity:'SSR',desc:'防45 次ガッツ25'},
c_ssr6:{name:'弱体の壺',cost:0,weak:3,vuln:3,remove:true,rarity:'SSR',desc:'3T攻弱守弱 消滅'},
c_ssr7:{name:'ホリィの教え',cost:65,currentTurnDouble:true,rarity:'SSR',desc:'今与ダメ2倍'},
c_ssr8:{name:'コルトの教え',cost:10,currentTurnBlockDouble:true,rarity:'SSR',desc:'今ブロック2倍'},
c_mr1:{name:'ホリィの極意',cost:10,atkBattle:10,regenEnergy:5,remove:true,rarity:'MR',desc:'力10 毎G5 消滅'},
c_mr2:{name:'コルトの極意',cost:10,blockBattle:10,regenBlock:5,remove:true,rarity:'MR',desc:'丈10 枚毎防5 消滅'},
c_mr3:{name:'ガッツ解放！！',cost:0,instantEnergy:25,maxEnergyBattle:25,remove:true,rarity:'MR',desc:'ガッツ25回復 最大25 消滅'},
c_mr4:{name:'極ガッツヒール',cost:0,instantEnergy:20,draw:1,rarity:'MR',desc:'ガッツ20回復 ドロー1'},
k_mr4:{mid:'kawazumo',name:'命を燃やせ…',cost:60,val:250,crit:'S',selfDmg:70,rarity:'MR',desc:'攻250 会心S 自傷70'},
ga_mr4:{mid:'gali',name:'ゴッドプロテクト',cost:0,block:40,blockBattle:5,regenBlock:10,regenDraw:1,remove:true,rarity:'MR',desc:'防40 丈夫さ5 毎防10 毎ターンドロー1 消滅'},
c_sr6:{name:'ガードフォース',cost:0,block:15,regenBlock:5,blockBattle:3,remove:true,rarity:'SR',desc:'防15 毎防5 丈夫さ3 消滅'},
c_sr7:{name:'ライフヒール',cost:30,heal:20,remove:true,rarity:'SR',desc:'回復20 消滅'},
c_ssr9:{name:'超ライフヒール',cost:45,heal:30,remove:true,rarity:'SSR',desc:'回復30 消滅'},
c_mr5:{name:'モンスター大行進',cost:60,val:10,hits:5,block:25,crit:'B',weak:1,vuln:1,rarity:'MR',desc:'攻10 防25 会心B 連撃5 攻弱守弱1'},
// 合成専用カード
fuse_freria:{name:'フレリアの祝福',cost:0,heal:30,regenEnergy:10,regenHp:5,regenBlock:10,remove:true,rarity:'LR',fusion:true,desc:'回30 毎G10 毎HP5 毎防10 消滅'},
fuse_gadamon:{name:'ガダモンの祝福',cost:0,atkBattle:10,blockBattle:10,vuln:5,maxEnergyBattle:50,instantEnergy:50,remove:true,rarity:'LR',fusion:true,desc:'攻+10守+10 守弱5 最大G50 即G50 消滅'},
fuse_dora:{name:'ドラの祝福',cost:0,regenEnergy:15,regenDraw:1,burn:3,shock:3,freeze:3,remove:true,rarity:'LR',fusion:true,desc:'毎G15 毎1ドロー 炎上3 感電3 氷結3 消滅'},
fuse_final_flame:{name:'終焉の炎',cost:65,val:40,weak:1,vuln:1,hits:5,burn:1,rarity:'LR',fusion:true,desc:'攻30 攻弱守弱1 連撃5 炎上1'},
fuse_grand_cross:{name:'グランドクロス',cost:75,val:125,shock:3,freeze:3,block:50,rarity:'LR',fusion:true,desc:'攻200 感電3 氷結3 防50'},

m_mr4:{mid:'motchi',name:'桜もっさま',cost:52,val:65,crit:'A',block:40,critEnergy:20,rarity:'MR',desc:'攻65 防40 会心時ガッツ回復20'},
g_mr4:{mid:'golem',name:'渾身掌打',cost:60,val:85,crit:'B',block:29,comboDmg:35,rarity:'MR',desc:'攻85 防29 守弱時ダメージ35'},
mo_mr4:{mid:'monolith',name:'トリオビーム∞',cost:60,val:10,hits:6,crit:'D',blockBattle:2,rarity:'MR',desc:'攻10 連撃6 丈+2'},

// ==== ザン専用カード ====
z_n1:{mid:'zan',name:'くしざし',cost:7,val:16,crit:'G',rarity:'N',desc:'攻16'},
z_n2:{mid:'zan',name:'ブレードガード',cost:12,block:20,atkBattle:3,rarity:'N',desc:'防20 力+3'},
z_n3:{mid:'zan',name:'かげうち',cost:10,val:19,crit:'B',vuln:1,rarity:'N',desc:'攻19 守弱1'},
z_n4:{mid:'zan',name:'まきびし',cost:16,val:2,crit:'G',bleed:5,rarity:'N',desc:'攻2 出血5'},
z_n5:{mid:'zan',name:'忍刀',cost:20,val:29,crit:'B',bleed:1,weak:2,rarity:'N',desc:'攻29 出血1 攻弱2'},
z_r1:{mid:'zan',name:'ヒートヘイズ',cost:15,val:28,crit:'D',rarity:'R',desc:'攻28'},
z_r2:{mid:'zan',name:'ミラージュシフト',cost:21,val:25,crit:'D',block:24,rarity:'R',desc:'攻25 防24'},
z_r3:{mid:'zan',name:'スタナーブリッツ',cost:26,val:30,crit:'C',weak:2,vuln:2,rarity:'R',desc:'攻30 攻弱守弱2'},
z_r4:{mid:'zan',name:'ダブルサマー',cost:22,val:14,crit:'C',hits:2,bleed:1,rarity:'R',desc:'攻14 連撃2 出血1'},
z_r5:{mid:'zan',name:'ファストステップ',cost:17,regenEnergy:6,block:15,atkBattle:3,remove:true,rarity:'R',desc:'毎ターンガッツ回復6 防15 力+3 消滅'},
z_sr1:{mid:'zan',name:'メテオドライブ',cost:35,val:43,crit:'A',bleed:4,rarity:'SR',desc:'攻43 出血4'},
z_sr2:{mid:'zan',name:'セカンドステップ',cost:18,regenBlock:5,atkBattle:5,blockBattle:5,draw:2,remove:true,rarity:'SR',desc:'毎ターン防5 力丈+5 2ドロー 消滅'},
z_sr3:{mid:'zan',name:'ウィークショット',cost:14,val:14,crit:'A',bleedBonusMult:1,rarity:'SR',desc:'攻14 相手の出血と同じ追加ダメージ'},
z_sr4:{mid:'zan',name:'フォルダーブリッツ',cost:24,val:28,crit:'B',block:30,weak:2,vuln:2,rarity:'SR',desc:'攻28 防30 攻弱守弱2'},
z_sr5:{mid:'zan',name:'不撓不屈',cost:15,block:15,nextTurnEnergy:50,rarity:'SR',desc:'防15 次ガッツ50'},
z_ssr1:{mid:'zan',name:'アサルトレイド',cost:44,val:8,crit:'C',hits:5,bleed:1,rarity:'SSR',desc:'攻8 連撃5 出血1'},
z_ssr2:{mid:'zan',name:'ライジングレイヴ',cost:42,val:52,crit:'A',bleed:6,rarity:'SSR',desc:'攻52 出血6'},
z_ssr3:{mid:'zan',name:'アサルトステップ',cost:17,regenEnergy:12,atkBattle:5,blockBattle:5,draw:3,remove:true,rarity:'SSR',desc:'毎ターンガッツ回復12 力丈+5 3ドロー 消滅'},
z_ssr4:{mid:'zan',name:'ムラサメ',cost:50,val:52,crit:'C',bleed:3,bleedHealHalf:true,rarity:'SSR',desc:'攻52 出血3 相手の出血の半分ライフ回復'},
z_ssr5:{mid:'zan',name:'みがわり',cost:16,bleedBlock:true,nextTurnEnergy:25,rarity:'SSR',desc:'相手の出血の数だけブロック 次ガッツ25'},
z_mr1:{mid:'zan',name:'アクシズバレット',cost:50,val:25,crit:'S',hits:3,bleed:1,vuln:1,rarity:'MR',desc:'攻25 連撃3 出血1 守弱1'},
z_mr2:{mid:'zan',name:'ダークホウスト',cost:68,val:8,crit:'B',hits:5,bleed:1,bleedBonusMult:1,rarity:'MR',desc:'攻8 連撃5 出血1 相手の出血と同じ追加ダメージ'},
z_mr3:{mid:'zan',name:'血の契約',cost:100,selfDmg:15,draw:2,zeroCostHand:true,remove:true,rarity:'MR',desc:'自傷15 2ドロー 手札消費ガッツ0 消滅'},
z_mr4:{mid:'zan',name:'ブラッディレイヴ',cost:55,val:31,crit:'S',bleedBonusMult:3,rarity:'MR',desc:'攻31 相手の出血の3倍追加ダメージ'},

// ==== 追加カード群 ====
// モッチー
m_n6:{mid:'motchi',name:'気合いだめ',cost:15,kiaiTurns:1,rarity:'N',desc:'1T気合い状態(クリ率+30%)'},
m_r8:{mid:'motchi',name:'大もちき',cost:18,val:26,crit:'D',atkBattle:1,block:11,rarity:'R',desc:'攻26 会心D 力+1 防11'},
m_r9:{mid:'motchi',name:'お餅体制',cost:13,block:21,nextTurnEnergy:14,heal:3,rarity:'R',desc:'防21 次ガッツ14 ライフ3回復'},
m_sr9:{mid:'motchi',name:'桜ローリン',cost:28,val:9,crit:'C',hits:3,kiaiTurns:2,rarity:'SR',desc:'攻9 会心C 連撃3 2T気合い状態'},
m_sr10:{mid:'motchi',name:'会心の餅撃',cost:35,val:44,crit:'A',critEnergy:12,critWeak:2,critBlock:30,rarity:'SR',desc:'攻44 会心A クリ時ガッツ12回復・攻弱2・防30付与'},
m_ssr6:{mid:'motchi',name:'超気合いだめ',cost:24,maxEnergyBattle:3,kiaiTurns:2,critDmgBoostTurns:2,rarity:'SSR',desc:'ガッツ上限+3 2T気合い状態 2Tクリダメ+25%'},
m_ssr7:{mid:'motchi',name:'カチカチモチ',cost:22,block:50,drainReduceTurns:1,drainReduceAmt:15,rarity:'SSR',desc:'防50 1T受けるガッツダウン-15'},
m_mr5:{mid:'motchi',name:'もちもちヴェール',cost:21,regenBlock:8,regenHp:3,regenEnergy:10,blockBattle:5,remove:true,rarity:'MR',desc:'毎ターン防8・ライフ3回復・ガッツ10回復 丈夫さ+5 消滅'},
// ゴーレム
g_n6:{mid:'golem',name:'ダンベルアタック',cost:11,val:17,crit:'E',atkBattle:1,rarity:'N',desc:'攻17 会心E 力+1'},
g_r8:{mid:'golem',name:'お花摘み',cost:14,heal:7,nextTurnEnergy:30,remove:true,rarity:'R',desc:'ライフ7回復 次ガッツ30 消滅'},
g_r9:{mid:'golem',name:'のびーるパンチ',cost:18,val:27,crit:'D',block:11,weak:2,rarity:'R',desc:'攻27 会心D 防11 攻弱2'},
g_sr7:{mid:'golem',name:'ダンベルラッシュ',cost:26,val:17,crit:'C',hits:2,atkBattle:2,rarity:'SR',desc:'攻17 会心C 連撃2 力+2'},
g_sr8:{mid:'golem',name:'ロックラリアット',cost:38,val:51,crit:'B',executeBelow:0.5,executeMult:2,rarity:'SR',desc:'攻51 会心B 敵ライフ50%以下でダメージ2倍'},
g_ssr5:{mid:'golem',name:'力の誓い',cost:60,regenAtk:5,remove:true,rarity:'SSR',desc:'毎ターン力+5 消滅'},
g_ssr6:{mid:'golem',name:'握りつぶす',cost:41,val:49,crit:'B',weak:3,vuln:3,enemyAtkDown:5,rarity:'SSR',desc:'攻49 会心B 攻弱守弱3 相手力-5'},
g_mr5:{mid:'golem',name:'一撃入魂',cost:90,val:0,ikkiIssin:true,remove:true,rarity:'MR',desc:'この戦闘中、連撃のないカードのダメージ3倍 消滅'},
// モノリス
mo_n6:{mid:'monolith',name:'壁ブーメラン',cost:9,val:18,crit:'E',block:10,rarity:'N',desc:'攻18 会心E 防10'},
mo_r6:{mid:'monolith',name:'2連たおれこみ',cost:15,val:8,crit:'D',hits:2,rarity:'R',desc:'攻8 会心D 連撃2'},
mo_r7:{mid:'monolith',name:'ブロックアタック',cost:8,val:0,crit:'D',dmgEqualsBlock:true,rarity:'R',desc:'攻:現在のブロックと同値 会心D'},
mo_sr7:{mid:'monolith',name:'模様替え',cost:21,blockBattle:3,regenBlock:7,regenEnergy:5,remove:true,rarity:'SR',desc:'丈夫さ+3 毎ターン防7・ガッツ5回復 消滅'},
mo_sr8:{mid:'monolith',name:'連続針ぶっ刺し',cost:34,val:13,crit:'C',hits:3,bleed:3,rarity:'SR',desc:'攻13 会心C 連撃3 出血3'},
mo_ssr5:{mid:'monolith',name:'絶たおれこみ',cost:22,val:45,crit:'B',vuln:1,blockBattle:1,rarity:'SSR',desc:'攻45 会心B 守弱1 丈夫さ+1'},
mo_ssr6:{mid:'monolith',name:'ダイヤモンド補修',cost:35,block:70,heal:5,nextTurnEnergy:25,rarity:'SSR',desc:'防70 ライフ5回復 次ガッツ25'},
mo_mr5:{mid:'monolith',name:'絶対防御体制',cost:60,val:0,blockPersists:true,remove:true,rarity:'MR',desc:'この戦闘中、ブロックがターン開始時にリセットされなくなる 消滅'},
// カワズモー
k_n5:{mid:'kawazumo',name:'塩撒き',cost:8,val:4,crit:'G',weak:2,vuln:2,rarity:'N',desc:'攻4 会心G 攻弱守弱2'},
k_r5:{mid:'kawazumo',name:'つっぱり',cost:22,val:4,crit:'D',hits:4,rarity:'R',desc:'攻4 会心D 連撃4'},
k_r6:{mid:'kawazumo',name:'かわずはりて',cost:15,val:20,crit:'B',critDraw:1,rarity:'R',desc:'攻20 会心B クリ時1ドロー'},
k_sr6:{mid:'kawazumo',name:'柱稽古',cost:17,atkBattle:7,blockBattle:3,regenEnergy:3,remove:true,rarity:'SR',desc:'力+7 丈夫さ+3 毎ターンガッツ3回復 消滅'},
k_sr7:{mid:'kawazumo',name:'飛び頭突き',cost:29,val:70,crit:'C',selfDmg:10,rarity:'SR',desc:'攻70 会心C 自傷10'},
k_ssr6:{mid:'kawazumo',name:'カエル大合唱',cost:42,val:55,crit:'S',weak:2,vuln:2,freeze:1,bleed:10,rarity:'SSR',desc:'攻55 会心S 攻弱守弱2 氷結1 出血10'},
k_ssr7:{mid:'kawazumo',name:'渾身はりて',cost:25,val:54,crit:'B',rarity:'SSR',desc:'攻54 会心B'},
k_mr5:{mid:'kawazumo',name:'自己犠牲',cost:30,selfDmg:30,selfDmgCardsDoubled:true,rarity:'MR',desc:'自傷30 この戦闘中、自傷ダメージ持ちカードのダメージ3倍'},
// ガリ
ga_n5:{mid:'gali',name:'フック',cost:9,val:19,crit:'D',rarity:'N',desc:'攻19 会心D'},
ga_r5:{mid:'gali',name:'雷閃',cost:11,val:17,crit:'B',shock:1,rarity:'R',desc:'攻17 会心B 感電1'},
ga_r6:{mid:'gali',name:'フォースチャージ',cost:0,nextTurnEnergy:25,rarity:'R',desc:'次ガッツ25'},
ga_sr8:{mid:'gali',name:'ホーリーアース',cost:26,val:35,crit:'C',regenEnergy:3,rarity:'SR',desc:'攻35 会心C 毎ターンガッツ+3'},
ga_sr9:{mid:'gali',name:'ホーリーシャッター',cost:19,val:15,crit:'D',block:35,nextTurnEnergy:8,rarity:'SR',desc:'攻15 会心D 防35 次ガッツ8'},
ga_ssr5:{mid:'gali',name:'神の啓示',cost:50,godCoreActive:true,remove:true,rarity:'SSR',desc:'この戦闘中「神核」を付与(攻撃で神聖蓄積、5毎にガッツ15回復・ダメ10%アップ 最大50%) 消滅'},
ga_ssr6:{mid:'gali',name:'ゴッドアタック',cost:34,val:49,crit:'B',permDmgMultBonus:0.05,block:21,rarity:'SSR',desc:'攻49 会心B この戦闘中ダメージ+5%(累積) 防21'},
ga_mr5:{mid:'gali',name:'神の奇跡',cost:30,regenHp:5,godMiracleCostDown:true,draw:2,remove:true,rarity:'MR',desc:'毎ターンライフ5回復 「ゴッド」名のカードの消費ガッツ-5 2ドロー 消滅'},
// ヒノトリ
h_n5:{mid:'hinotori',name:'炎のくちばし',cost:9,val:20,crit:'D',rarity:'N',desc:'攻20 会心D'},
h_r6:{mid:'hinotori',name:'バーニングウィング',cost:12,val:24,crit:'C',burn:1,rarity:'R',desc:'攻24 会心C 炎上1'},
h_r7:{mid:'hinotori',name:'癒しの炎',cost:24,heal:15,block:15,rarity:'R',desc:'ライフ15回復 防15'},
h_sr6:{mid:'hinotori',name:'火の粉はらい',cost:28,cureDebuffs:true,heal:10,remove:true,rarity:'SR',desc:'自身の弱体効果を解除 ライフ10回復 消滅'},
h_sr7:{mid:'hinotori',name:'フレイムレーザー',cost:29,val:55,crit:'E',burn:1,rarity:'SR',desc:'攻55 会心E 炎上1'},
h_ssr6:{mid:'hinotori',name:'炎の極意',cost:55,enoOhActive:true,remove:true,rarity:'SSR',desc:'この戦闘中「炎王」を付与(炎上中の敵への攻撃でライフ2回復、炎上5超で+100、15超でさらに+100) 消滅'},
h_ssr7:{mid:'hinotori',name:'紅蓮のかぎづめ',cost:20,val:5,crit:'C',hits:3,draw:1,rarity:'SSR',desc:'攻5 会心C 連撃3 1ドロー'},
h_mr5:{mid:'hinotori',name:'バーニングオーラ',cost:37,atkBattle:10,blockBattle:10,regenEnergy:5,nextTurnEnergy:50,remove:true,rarity:'MR',desc:'力+10 丈夫さ+10 毎ターンガッツ5回復 次ガッツ50 消滅'},
// ザン
z_n6:{mid:'zan',name:'クナイ',cost:7,val:13,crit:'C',bleed:2,rarity:'N',desc:'攻13 会心C 出血2'},
z_r6:{mid:'zan',name:'影手裏剣',cost:14,val:7,crit:'B',hits:2,bleed:2,rarity:'R',desc:'攻7 会心B 連撃2 出血2'},
z_r7:{mid:'zan',name:'バニッシュブロウ',cost:42,val:21,crit:'D',bleed:3,grantEvasion:1,rarity:'R',desc:'攻21 会心D 出血3 回避1付与'},
z_sr6:{mid:'zan',name:'バレットスナイプ',cost:28,val:38,crit:'S',critBonusDmg:35,rarity:'SR',desc:'攻38 会心S クリ時追加ダメージ35'},
z_sr7:{mid:'zan',name:'マルチスティング',cost:37,val:4,crit:'C',hits:4,bleed:1,rarity:'SR',desc:'攻4 会心C 連撃4 出血1'},
z_ssr6:{mid:'zan',name:'精神統一',cost:34,atkBattle:6,costReducePct:15,remove:true,rarity:'SSR',desc:'力+6 この戦闘中消費ガッツ-15% 消滅'},
z_ssr7:{mid:'zan',name:'スラッシュロンド',cost:55,val:11,crit:'D',hits:4,bleed:2,weak:2,rarity:'SSR',desc:'攻11 会心D 連撃4 出血2 攻弱2'},
z_mr5:{mid:'zan',name:'ブラッディワルツ',cost:38,regenHp:3,selfBleedOnHit:1,permDmgMultBonus:0.15,remove:true,rarity:'MR',desc:'毎ターンライフ3回復 今後の攻撃に出血+1 ダメージ+15% 消滅'},
// 共通
c_r9:{name:'スラッシュ',cost:12,val:15,crit:'D',bleed:4,rarity:'R',desc:'攻15 会心D 出血4'},
c_r10:{name:'フローズンショット',cost:15,val:24,crit:'C',freeze:1,weak:1,rarity:'R',desc:'攻24 会心C 氷結1 攻弱1'},
c_r11:{name:'エレキブロウ',cost:11,val:12,crit:'B',shock:1,vuln:1,rarity:'R',desc:'攻12 会心B 感電1 守弱1'},
c_r12:{name:'フレアウィップ',cost:17,val:30,crit:'E',burn:1,rarity:'R',desc:'攻30 会心E 炎上1'},
c_sr8:{name:'万能薬',cost:15,statusImmune:1,remove:true,rarity:'SR',desc:'状態異常無効を1個付与(攻弱・守弱・手札減少・消費ガッツ増加・出血を1回無効化) 消滅'},
c_sr9:{name:'超修行',cost:30,tempUpgradeHand:true,rarity:'SR',desc:'手札の他のカードを強化状態にする(戦闘終了時に解除)'},
c_ssr10:{name:'アイスブレイク',cost:27,val:44,crit:'C',freeze:1,vuln:2,rarity:'SSR',desc:'攻44 会心C 氷結1 守弱2'},
c_ssr11:{name:'スパークハンマー',cost:31,val:55,crit:'S',shock:1,rarity:'SSR',desc:'攻55 会心S 感電1'},
c_ssr12:{name:'炎の鱗粉',cost:45,val:28,crit:'B',hits:2,burn:1,block:32,rarity:'SSR',desc:'攻28 会心B 連撃2 炎上1 防32'},
c_ssr13:{name:'グランドウォール',cost:22,block:35,heal:10,nextTurnEnergy:12,rarity:'SSR',desc:'防35 ライフ10回復 次ガッツ12'},
c_ssr14:{name:'厄払い',cost:50,cureDebuffs:true,remove:true,rarity:'SSR',desc:'自身の弱体効果を全て解除 消滅'},
c_mr6:{name:'無念無双',cost:31,val:39,crit:'B',hits:3,randomExhaustHand:1,rarity:'MR',desc:'攻39 会心B 連撃3 手札からランダムに1枚消滅'},
c_mr7:{name:'三日月の舞',cost:62,grantEvasion:2,remove:true,rarity:'MR',desc:'回避2を付与 消滅'},
// ==== 消滅系(手札を整理するカード) ====
// chooseExhaust: 手札から何枚選んで消滅させるか。選ばせるUIは index.html の「手札消滅の選択モード」。
// exhaustHandAll: 手札を全部消滅。drawPerExhausted: 消滅した枚数ぶんドロー。
// energyFromExhausted: 消滅させたカードのコスト合計ぶんガッツを得る。
// **4枚とも remove:true(使ったら消滅)。** これを外すと「引く→捨てる→引く」が無限に回るため。
c_r13:{name:'選別',cost:11,chooseExhaust:1,draw:1,rarity:'R',desc:'手札から1枚選んで消滅 ドロー1'},
c_sr10:{name:'昇華',cost:12,chooseExhaust:1,energyFromExhausted:true,remove:true,rarity:'SR',desc:'手札から1枚選んで消滅 そのカードのコストぶんガッツ回復 消滅'},
c_sr11:{name:'整理整頓',cost:15,exhaustHandAll:true,drawPerExhausted:true,remove:true,rarity:'SR',desc:'手札を全て消滅 消滅した枚数ぶんドロー 消滅'},
c_ssr15:{name:'忘却の礎',cost:8,chooseExhaust:2,draw:1,heal:30,remove:true,rarity:'SSR',desc:'手札から2枚選んで消滅 ドロー1 回復30 消滅'},

// ==== スキン専用の技セット ====
// skinSetOf で「どのスキンのセットか」、replaces で「どのカードと入れ替わるか」を指定する。
// isStarter の専用技(skinCardOf)と違い、こちらは報酬・ショップ・イベントも含めた
// 全ての入手経路で入れ替わる。冒険を始めるときに使うかどうかを決め、途中では変わらない。
// 【重要】レア度は元カードと揃えること。揃えないと報酬の抽選枠がズレて出現率が変わる。
// ---- ゴジョモッチー(motchi_ssr_02) ----
m_r9_gojo:{mid:'motchi',id:'m_r9_gojo',name:'大丈夫僕最強だから',cost:20,block:20,regenEnergy:20,remove:true,rarity:'R',
  desc:'防20 毎ターンガッツ+20 消滅',skinSetOf:'motchi_ssr_02',replaces:'m_r9',motion:'def_ring'},
m_r1_gojo:{mid:'motchi',id:'m_r1_gojo',name:'術式順転「蒼」',cost:24,val:45,vuln:1,crit:'D',rarity:'R',
  desc:'攻45 守弱1',skinSetOf:'motchi_ssr_02',replaces:'m_r1',motion:'deb_bind'},
m_sr5_gojo:{mid:'motchi',id:'m_sr5_gojo',name:'術式反転「赫」',cost:55,val:70,comboDmg:150,crit:'B',rarity:'SR',
  desc:'攻70 守弱時ダメージ+150',skinSetOf:'motchi_ssr_02',replaces:'m_sr5',motion:'atk_burst'},
m_mr1_gojo:{mid:'motchi',id:'m_mr1_gojo',name:'虚式「茈」',cost:75,val:150,hits:2,vuln:1,comboDmg:150,crit:'A',remove:true,rarity:'MR',
  desc:'攻150 連撃2 守弱1 守弱時ダメージ+150 消滅',skinSetOf:'motchi_ssr_02',replaces:'m_mr1',motion:'atk_flash'},
m_mr2_gojo:{mid:'motchi',id:'m_mr2_gojo',name:'領域展開「無量空処」',cost:80,block:80,regenBlock:20,freeze:5,vuln:5,weak:5,kiaiTurns:5,permDmgMultBonus:0.25,remove:true,rarity:'MR',
  desc:'防80 毎T防20 氷結5 守弱5 攻弱5 5T気合い状態(会心率+30%) この戦闘中ダメージ+25% 消滅',skinSetOf:'motchi_ssr_02',replaces:'m_mr2',motion:'buf_awaken'},

// ---- ゲコウスグル(kawazumo_ssr_02) ----
// 「呪霊」は戦闘中だけ溜まるカウンター(state.player.curse)。戦闘が終わると0に戻る。
//   curse:N       … 呪霊を N 溜める（攻撃を撃った「後」に溜まるので、自分のcurseDmgは強化しない）
//   curseDmg:N    … 追加ダメージ 呪霊×N。カードの攻・力と同じ場所に足すので守弱1.5倍と会心もそのまま乗る
//   curseSpend    … 撃ったあと呪霊を0に戻す
//   regenCurse:N  … 毎ターン開始時に呪霊+N
// 【重要】curseDmg は playCard と calcPreviewDmg の両方に同じ式を書くこと。片方だけだと表示と実際がズレる。
k_r4_geto:{mid:'kawazumo',id:'k_r4_geto',name:'呪霊吸収',cost:11,block:8,nextTurnEnergy:8,curse:4,rarity:'R',
  desc:'防8 次G8 呪霊+4',skinSetOf:'kawazumo_ssr_02',replaces:'k_r4',motion:'def_hex'},
k_r1_geto:{mid:'kawazumo',id:'k_r1_geto',name:'呪霊操術・蝿頭',cost:14,val:12,vuln:1,curse:2,curseDmg:5,crit:'D',rarity:'R',
  desc:'攻12 守弱1 呪霊×5追加ダメージ 呪霊+2',skinSetOf:'kawazumo_ssr_02',replaces:'k_r1',motion:'deb_corrode'},
k_sr4_geto:{mid:'kawazumo',id:'k_sr4_geto',name:'呪霊操術・虹龍',cost:34,val:34,block:18,curse:4,curseDmg:10,crit:'C',rarity:'SR',
  desc:'攻34 防18 呪霊×10追加ダメージ 呪霊+4',skinSetOf:'kawazumo_ssr_02',replaces:'k_sr4',motion:'atk_slash'},
k_mr4_geto:{mid:'kawazumo',id:'k_mr4_geto',name:'極ノ番「うずまき」',cost:60,val:50,curseDmg:30,curseSpend:true,crit:'B',rarity:'MR',
  desc:'攻50 呪霊×30追加ダメージ 呪霊を全て放つ',skinSetOf:'kawazumo_ssr_02',replaces:'k_mr4',motion:'atk_burst'},
k_mr3_geto:{mid:'kawazumo',id:'k_mr3_geto',name:'盤星教の教祖',cost:26,curse:4,regenCurse:3,regenEnergy:8,remove:true,rarity:'MR',
  desc:'呪霊+4 毎ターン呪霊+3 毎ターンガッツ回復8 消滅',skinSetOf:'kawazumo_ssr_02',replaces:'k_mr3',motion:'buf_sigil'},

// ==== イブリース専用カード（実装中の種族） ====
// 形態のルール:
//   通常形態 … 受けるダメージ0.9倍 / 毎ターンのガッツ回復+6
//   天使型　 … 与えるダメージ1.2倍 / 受けるダメージ1.1倍
//   formTo : 'angel' / 'normal' / 'toggle'  → カードの効果が全部終わったあとに変身する
//   formEff: その形態で「使ったとき」だけ差し替わる値。数値の上書きで、説明文は上書きしない。
// 【重要】説明文(desc)には必ず両方の形態ぶんを書くこと。
//   出ている数値は「いまの形態のもの」だが、プレイヤーは変身前に反対側の値も知りたい。
//   【天】= 天使型で使ったとき / 【通】= 通常形態で使ったとき
ib_n1:{mid:'iblis',name:'黄泉の一撃',cost:7,val:16,crit:'F',rarity:'N',desc:'攻16'},
ib_n2:{mid:'iblis',name:'昇華の翼',cost:10,val:14,crit:'D',formTo:'angel',rarity:'N',desc:'攻14 使用後 天使型になる'},
ib_n3:{mid:'iblis',name:'闇衣',cost:11,block:18,nextTurnEnergy:8,formTo:'normal',rarity:'N',desc:'防18 次ガッツ8 使用後 通常形態になる'},
ib_n4:{mid:'iblis',name:'神光の欠片',cost:9,val:15,crit:'E',formEff:{angel:{val:22}},rarity:'N',desc:'攻15 【天】攻22'},
ib_n5:{mid:'iblis',name:'静かな祈り',cost:6,nextTurnEnergy:14,formEff:{normal:{nextTurnEnergy:22}},rarity:'N',desc:'次ガッツ14 【通】次ガッツ22'},
ib_n6:{mid:'iblis',name:'呪縛の指先',cost:13,val:10,crit:'F',weak:1,vuln:1,rarity:'N',desc:'攻10 攻弱守弱1'},
ib_r1:{mid:'iblis',name:'熾天の羽ばたき',cost:18,val:30,crit:'D',formTo:'angel',rarity:'R',desc:'攻30 使用後 天使型になる'},
ib_r2:{mid:'iblis',name:'黄泉還り',cost:16,block:22,heal:5,formTo:'normal',rarity:'R',desc:'防22 回5 使用後 通常形態になる'},
ib_r3:{mid:'iblis',name:'二律の刃',cost:20,val:20,block:22,crit:'D',formEff:{angel:{hits:2,block:0}},rarity:'R',desc:'攻20 防22 【天】攻20 連撃2(防なし)'},
ib_r4:{mid:'iblis',name:'神光よ汚れを祓え',cost:22,val:28,crit:'C',vuln:1,formEff:{angel:{val:38}},rarity:'R',desc:'攻28 守弱1 【天】攻38'},
ib_r5:{mid:'iblis',name:'深淵の護り',cost:17,block:26,nextTurnEnergy:13,formEff:{normal:{block:34,nextTurnEnergy:20,blockBattle:2}},rarity:'R',desc:'防26 次ガッツ13 【通】防34 次ガッツ20 丈+2'},
ib_r6:{mid:'iblis',name:'翔べ震律の刃よ',cost:21,val:13,hits:2,crit:'C',formEff:{angel:{hits:3}},rarity:'R',desc:'攻13 連撃2 【天】連撃3'},
ib_r7:{mid:'iblis',name:'反転の呼吸',cost:12,draw:1,nextTurnEnergy:10,formTo:'toggle',rarity:'R',desc:'1ドロー 次ガッツ10 使用後 形態が入れ替わる'},
ib_sr1:{mid:'iblis',name:'熾天の剣よ降り立て',cost:34,val:11,hits:3,crit:'C',formTo:'angel',formEff:{angel:{hits:4,weak:1}},rarity:'SR',desc:'攻11 連撃3 使用後 天使型になる 【天】連撃4 攻弱1'},
ib_sr2:{mid:'iblis',name:'聖光よ奇跡を灯せ',cost:30,val:30,crit:'B',heal:15,formEff:{angel:{val:40,heal:20}},rarity:'SR',desc:'攻30 回15 【天】攻40 回20'},
ib_sr3:{mid:'iblis',name:'黄泉の根源に従え',cost:18,val:25,block:40,crit:'D',regenBlock:8,formTo:'normal',remove:true,rarity:'SR',desc:'攻25 防40 毎ターン防8 使用後 通常形態になる 消滅'},
ib_sr4:{mid:'iblis',name:'導け神光の道標',cost:26,val:25,crit:'B',vuln:2,formTo:'angel',formEff:{angel:{val:37,vuln:3}},rarity:'SR',desc:'攻25 守弱2 使用後 天使型になる 【天】攻37 守弱3'},
ib_sr5:{mid:'iblis',name:'天秤',cost:20,draw:2,atkBattle:1,blockBattle:1,formTo:'toggle',rarity:'SR',desc:'2ドロー 力丈+1 使用後 形態が入れ替わる'},
ib_sr6:{mid:'iblis',name:'冥き福音',cost:24,val:20,crit:'D',weak:2,nextTurnEnergy:12,formEff:{normal:{val:0,block:30,weak:3,nextTurnEnergy:24}},rarity:'SR',desc:'攻20 攻弱2 次ガッツ12 【通】防30 攻弱3 次ガッツ24(攻なし)'},
ib_sr7:{mid:'iblis',name:'双極',cost:32,val:34,block:34,crit:'C',formTo:'toggle',formEff:{angel:{val:51,block:10}},rarity:'SR',desc:'攻34 防34 使用後 形態が入れ替わる 【天】攻51 防10'},
ib_ssr1:{mid:'iblis',name:'天の慈悲よ示されよ',cost:44,val:16,hits:3,crit:'C',dmgCutPct:20,dmgCutTurns:2,formTo:'angel',formEff:{angel:{hits:4}},rarity:'SSR',desc:'攻16 連撃3 2ターン受けるダメージ20%カット 使用後 天使型になる 【天】連撃4'},
ib_ssr2:{mid:'iblis',name:'終焉に救いを与えよ',cost:46,val:58,crit:'A',vuln:2,formEff:{angel:{val:72,burn:1}},rarity:'SSR',desc:'攻58 守弱2 【天】攻72 炎上1'},
ib_ssr3:{mid:'iblis',name:'黄泉の甲冑',cost:20,block:45,blockBattle:8,regenEnergy:15,formTo:'normal',remove:true,rarity:'SSR',desc:'防45 丈+8 毎ターンガッツ15 使用後 通常形態になる 消滅'},
ib_ssr4:{mid:'iblis',name:'熾天使化',cost:30,atkBattle:8,draw:3,heal:50,formTo:'angel',remove:true,rarity:'SSR',desc:'力+8 3ドロー 回50 使用後 天使型になる 消滅'},
ib_ssr5:{mid:'iblis',name:'世界を揺らせ',cost:40,val:20,hits:3,crit:'B',weak:2,vuln:2,formEff:{normal:{val:0,hits:1,weak:0,vuln:0,block:35,nextTurnEnergy:12}},rarity:'SSR',desc:'攻20 連撃3 攻弱守弱2 【通】防35 次ガッツ12(攻なし)'},
ib_ssr6:{mid:'iblis',name:'二相の福音',cost:48,block:65,regenBlock:6,formEff:{angel:{block:0,regenBlock:0,val:85,crit:'A',vuln:2}},rarity:'SSR',desc:'防65 毎ターン防6 【天】攻85 会心A 守弱2(防なし)'},
ib_ssr7:{mid:'iblis',name:'今こそ真なる目覚め',cost:14,atkBattle:6,blockBattle:6,regenEnergy:12,formTo:'toggle',remove:true,rarity:'SSR',desc:'力丈+6 毎ターンガッツ12 使用後 形態が入れ替わる 消滅'},
ib_mr1:{mid:'iblis',name:'神光の裁き',cost:60,val:46,hits:2,crit:'S',vuln:2,formTo:'angel',formEff:{angel:{val:60,weak:2}},rarity:'MR',desc:'攻46 連撃2 守弱2 使用後 天使型になる 【天】攻60 攻弱2'},
ib_mr2:{mid:'iblis',name:'黄泉の根源、開闢',cost:31,block:55,regenBlock:10,blockBattle:10,formTo:'normal',remove:true,rarity:'MR',desc:'防55 毎ターン防10 丈+10 使用後 通常形態になる 消滅'},
ib_mr3:{mid:'iblis',name:'二律背反',cost:70,val:60,block:60,crit:'A',formEff:{angel:{hits:2,block:20}},rarity:'MR',desc:'攻60 防60 【天】攻60 連撃2 防20'},
ib_mr4:{mid:'iblis',name:'熾天顕現',cost:42,atkBattle:10,draw:2,permDmgMultBonus:0.2,formTo:'angel',remove:true,rarity:'MR',desc:'力+10 2ドロー この戦闘中ダメージ+20% 使用後 天使型になる 消滅'},
ib_mr5:{mid:'iblis',name:'終焉と再誕',cost:72,val:90,crit:'S',weak:3,vuln:3,heal:25,formTo:'toggle',rarity:'MR',desc:'攻90 攻弱守弱3 回25 使用後 形態が入れ替わる'},
};
